language: node_js

node_js:
  - "11"
  - "10"
  - "8"

cache: npm

before_install:
  - npm install -g greenkeeper-lockfile

install: npm ci

before_script:
  - greenkeeper-lockfile-update
  - npm run lint:js
  - npm run lint:css

after_script:
  - greenkeeper-lockfile-upload

after_success:
  - npm run lighthouse

branches:
  only:
    - master
    - /^greenkeeper\/.*$/
