language: node_js
node_js:
  - "8.11.1"

before_install: npm install -g greenkeeper-lockfile
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

branches:
  only:
    - master
    - /^greenkeeper\/.*$/
