[build]
  command = "npm run build"
  publish = "_site"

[context.production.environment]
  NODE_ENV = "production"

[[headers]]
  for = "/static/*"

  [headers.values]
    Cache-Control = "max-age=31536000, immutable"
