[build]
  publish = "build"
  command = "npm run build"

[[headers]]
  for = "/*"

[headers.values]
  Cache-Control = "public,max-age=31536000"

[[redirects]]
  from = "/api/*"
  query = {page = ":page"}
  to = "/api/:splat/pages/:page.json"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/api/:splat.json"
  status = 200

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
