[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  API_PAGE_FORMAT = "?page={page}"

  # It looks like empty string values for env variables are being ignored,
  # so I'm setting this to some value that gets manually checked in the build
  # code where the default value is manually set.
  API_PATH_EXTENSION = "[none]"

[[headers]]
  for = "/*"

[headers.values]
  Cache-Control = "public,max-age=31536000"

# Rewrite `/api/articles?page=1` to `/api/articles/pages/1.json`
[[redirects]]
  from = "/api/*"
  query = {page = ":page"}
  to = "/api/:splat/pages/:page.json"
  status = 200

# Rewrite `/api/articles` to `/api/articles.json`
[[redirects]]
  from = "/api/*"
  to = "/api/:splat.json"
  status = 200

# Rewrite all other paths to root
[[redirects]]
  from = "/*"
  to = "/"
  status = 200
